---
layout: post
title:  "managing callback function"
excerpt: "reviews"


categories:
  - Blog
tags:
  - [Blog, jekyll, Github, Git]

 
date: 2021-08-10
last_modified_at: 2021-08-10
---

![image](https://user-images.githubusercontent.com/74404132/128819323-63d44496-f944-4b37-b9d5-1c8b24ff6f00.png)


변수처럼 함수 만들기

let f = function(param) {
    return param + 1
}

변수처럼 화살표 함수 만들기

let yellow = ( (...param) => 
            {
                return param[1]
            })


화살표 함수 : 

let func = ( (parameter) => { //body } )

함수 실행할 때 f(3) 처럼 사용한다
f((받을거) => {내용물과 리턴문})


<img width="766" alt="image" src="https://user-images.githubusercontent.com/74404132/128824454-15b7c8b8-4cd4-4519-a6ca-20ece0abbbb2.png">

        let print  = ( (...el) => { (el.forEach( (...param) => console.log(param[0]) ) )})
        print(1,2,3,4)


// forEach 반복문은 Array, Map, Set 에서 사용가능한 메서드이다

        let enumu = [1,2,3];
        enumu.forEach( (el, idx, arr) => { console.log(el) } );

arrow function inside an object
        let obj = {
            hi : () => {console.log(1) }
        }

setTimeout(f, 1000) 은 지정한 시간이 지나면 콜백함수 f를 시작하는 것

콜백함수란 ?  다른 코드의 인자로 넘겨주는 함수

'''' 그 제어권도 함께 위임한다. '''

https://velog.io/@minidoo/자바스크립트-콜백-함수Callback-Function-w8ipl698

![image](https://user-images.githubusercontent.com/74404132/128830050-c6826212-1eba-40e8-a5e7-5700445ec793.png)

new Promise 로 함수 만들었을때 ''' 안에 res, rej 있으면'' then으로 안넘어간다.

근데 아예 안넘기면 코드 안돌아가니
이렇게 실패하면 then 으로 다음 실행 하지 말고 .catch(로 빠지게 한다.)


let func = ( (n) => {
    let num = new Promise( (resolve, reject) => {
        if(n > 10){
            resolve('y')
        }
        else reject('no')
    }

    )
    return num
})




func(4).then(console.log(1)).catch(err => {console.log(err)})


이렇게 콜백 함수 기다리고 실행하라구

        let a = ( () =>{
            let c = async() => {
            return await setTimeout(obj.hi(), 1000)
            }
            return c
        }
        )

        a()

https://www.youtube.com/watch?v=s1vpVCrT8f4
영상은 10분 까지.